question_data = [{"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
                  "question": "Snakes and Ladders was originally created in India?",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "Leonardo DiCaprio won an Oscar for Best Actor in 2004&#039;s 'The Aviator'.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "The very first recorded computer 'bug' was a moth found inside a Harvard Mark II "
                              "computer.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "The M41 Walker Bulldog remains in service in some countries to this day.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "'Undertale' is an RPG created by Toby Fox and released in 2015.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "Israel is 7 hours ahead of New York.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "Pointers were not used in the original C programming language; they were added later "
                              "on in C++.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                  "question": "The Japanese Shinkansen beat the French TGV&#039;s speed record for fastest electric "
                              "rail train.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                  "question": "A defibrillator is used to start up a heartbeat once a heart has stopped beating.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Alaska is the largest state in the United States.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The United States was a member of the League of Nations.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Metal Gear Solid V: The Phantom Pain runs on the Fox Engine.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "In Kingdom Hearts the Paopu fruit is said to intertwine the destinies for two people "
                              "forever.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "A bear does NOT defecate during hibernation. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The average woman is 5 inches 13 centimeters shorter than the average man.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "easy",
                  "question": "Denmark has a monarch.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "Sitting for more than three hours a day can cut two years off a person&#039;s life "
                              "expectancy.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and "
                              "after filming.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In the 'Melancholy of Haruhi Suzumiya' series, the narrator goes by the nickname Kyon.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Gadgets", "type": "boolean", "difficulty": "medium",
                  "question": "The Western Electric Model 500 telephone uses tone dialing to dial phone numbers.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "Rabbits are rodents.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "In the game 'Subnautica', a 'Spadefish' will attack you.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "hard",
                  "question": "Joko Widodo has appeared in the cover of a TIME magazine.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                  "question": "The General Motors EV1 was the first street-legal production electric vehicle.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Mythology", "type": "boolean", "difficulty": "easy",
                  "question": "According to Greek Mythology, Atlas was an Olympian God.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
                  "question": "E = MC3", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "A caterpillar has more muscles than humans do.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "In Riot Games 'League of Legends' the name of Halloween event is called 'The "
                              "Reckoning'.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "Adolf Hitler was tried at the Nuremberg trials.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Television", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Klingons once had a period of Democracy in their history, they referred to it as the "
                              "'Dark Times'.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "easy",
                  "question": "In Rugby League, performing a '40-20' is punished by a free kick for the opposing team.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                  "question": "Sugar contains fat.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
                  "question": "The set of all algebraic numbers is countable.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "hard",
                  "question": "L&#039;H&ocirc;pital was the mathematician who created the homonymous rule that uses "
                              "derivatives to evaluate limits with indeterminations.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "hard",
                  "question": "Pete Townshend&#039;s solo album, 'White City: A Novel', is set in the metropolitan "
                              "area of Chicago.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Scotland voted to become an independent country during the referendum from September "
                              "2014.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "Haggis is traditionally ate on Burns Night.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "The scrapped Sonic the Hedgehog 2 level 'Hidden Palace Zone' was later reused in the "
                              "iOS port of the game. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "'Foodfight!' earned less than $80,000 at box office.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "The Korean War ended in 1953 without any ceasefire.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                  "question": "A Facebook campaign placed Rage Against The Machine&#039;s 'Killing in the Name Of' as "
                              "the UK Christmas Number 1 in 2009.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The commercial UK channel ITV stands for 'International Television'.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                  "question": "John Williams composed the music for 'Star Wars'.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Codemasters is the developer of the Gran Turismo series.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "There are 2 player roles in Trouble in Terrorist Town.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
                  "question": "The Paradox Interactive game 'Stellaris' was released in 2016.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                  "difficulty": "hard",
                  "question": "The protagonist in 'Humanity Has Declined' has no discernable name and is simply "
                              "referred to as &#039;I&#039; for most of the series.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}
                 ]
